 const atividadesMockadas = [
        {
            atividade: "Atividade 1",
            loginUsuario: "usuario1",
            cLoginResponsavel: 123,
            cProjeto: 456,
            cStatus: 1,
            cSprint: 789,
            cTipo: 2,
            dificuldade: 3,
            prioridade: 1,
            dataCriacao: "2024-04-06",
            dataInicial: "2024-04-08",
            descricao: "Descrição da atividade 1",
            dataFinal: "2024-04-12",
            codigo: 1,
        },
        {
            atividade: "Atividade 2",
            loginUsuario: "usuario1",
            cLoginResponsavel: 123,
            cProjeto: 456,
            cStatus: 2,
            cSprint: 789,
            cTipo: 2,
            dificuldade: 2,
            prioridade: 2,
            dataCriacao: "2024-04-06",
            dataInicial: "2024-04-10",
            descricao: "Descrição da atividade 2",
            dataFinal: "2024-04-15",
            codigo: 2,
        },
        {
            atividade: "Atividade 3",
            loginUsuario: "usuario1",
            cLoginResponsavel: 123,
            cProjeto: 456,
            cStatus: 2,
            cSprint: 789,
            cTipo: 2,
            dificuldade: 2,
            prioridade: 2,
            dataCriacao: "2024-04-06",
            dataInicial: "2024-04-10",
            descricao: "Descrição da atividade 3",
            dataFinal: "2024-04-15",
            codigo: 3,
        },
        {
            atividade: "Atividade 4",
            loginUsuario: "usuario1",
            cLoginResponsavel: 123,
            cProjeto: 456,
            cStatus: 2,
            cSprint: 789,
            cTipo: 2,
            dificuldade: 2,
            prioridade: 2,
            dataCriacao: "2024-04-06",
            dataInicial: "2024-04-10",
            descricao: "Descrição da atividade 4",
            dataFinal: "2024-04-15",
            codigo: 4,
        },
    ];

    export default atividadesMockadas;